# default root level, overrided for package and for the LoggingTest class:
level = FINE
#controladors
handlers = java.util.logging.FileHandler, java.util.logging.ConsoleHandler
# configuració del controlador de tipus fitxer
java.util.logging.FileHandler.level = WARNING
java.util.logging.FileHandler.pattern = ./log/app%g.log
java.util.logging.FileHandler.limit = 1024
java.util.logging.FileHandler.count = 3
java.util.logging.FileHandler.formatter = java.util.logging.XMLFormatter
java.util.logging.FileHandler.append = true
# configuració del controlador de tipus consola
java.util.logging.ConsoleHandler.level = INFO
java.util.logging.ConsoleHandler.formatter = java.util.logging.SimpleFormatter