handlers = java.util.logging.ConsoleHandler, java.util.logging.FileHandler

.level = INFO

# Consola
java.util.logging.ConsoleHandler.level = INFO
java.util.logging.ConsoleHandler.formatter = java.util.logging.SimpleFormatter

# Fitxer (rotació)
java.util.logging.FileHandler.pattern = files/filesRev/%gBanc.log
java.util.logging.FileHandler.limit = 5000
java.util.logging.FileHandler.count = 5
java.util.logging.FileHandler.append = true
java.util.logging.FileHandler.level = ALL
java.util.logging.FileHandler.formatter = java.util.logging.XMLFormatter